version: "3"

services:
  web:
    container_name: web
    build: .
    networks:
      - appnet
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      - roach0
      - roach1
      - roach2
  roach0:
    container_name: roach0
    image: cockroachdb/cockroach:v2.1.5
    hostname: roach0
    command: start --insecure
    networks:
      - appnet
      - roachnet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - ${PWD}/cockroach-data/roach0:/cockroach/cockroach-data
  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:v2.1.5
    hostname: roach1
    command: start --insecure --join=roach0
    networks:
      - roachnet
    volumes:
      - ${PWD}/cockroach-data/roach1:/cockroach/cockroach-data
    depends_on:
      - roach0
  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:v2.1.5
    hostname: roach2
    command: start --insecure --join=roach0
    networks:
      - roachnet
    volumes:
      - ${PWD}/cockroach-data/roach2:/cockroach/cockroach-data
    depends_on:
      - roach0

networks:
  appnet:
  roachnet:
