# Taken from https://github.com/cockroachdb/cockroach.
# Updated the namespace and name.
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroach-init
  namespace: hotel-management
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cockroach-init
        image: cockroachdb/cockroach:v2.1.5
        imagePullPolicy: IfNotPresent
        command:
        - "/cockroach/cockroach"
        - "init"
        - "--insecure"
        - "--host=cockroachdb-0.cockroachdb"
      restartPolicy: OnFailure
