version: 2

# See https://circleci.com/docs/2.0/language-java/ for more information.
# This pretty closely resembles the sample config.

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/hotelmanagement
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test
