apiVersion: v1
kind: Service
metadata:
  name: hotel-management-web-public
  namespace: hotel-management
  labels:
    app: hotel-management
spec:
  selector:
    app: hotel-management
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-management-web
  namespace: hotel-management
  labels:
    app: hotel-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-management
  template:
    metadata:
      labels:
        app: hotel-management
    spec:
      containers:
        - name: web
          image: hotelmanagement_web:latest
          command: ["/bin/sh"]
          args: ["-c", "exec /run.sh prod"]
          ports:
            - containerPort: 9000
          imagePullPolicy: Never